language: node_js
sudo: false
node_js:
  - 'stable'
  - 'lts/*'
  - '8'

before_deploy:
  - mkdir _deploy
  - cp -R examples _deploy/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: _deploy
  on:
    branch: master
    node: stable
