name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install
      - name: Check code style
        run: npm run lint
  test:
    name: Tests
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x, 22.x, 24.x]
        react-version: [17.x]
        include:
          - node-version: 16.x
            react-version: 16.0.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
      - name: Install Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v6
        with:
          node-version: ${{matrix.node-version}}
      - name: Install dependencies
        run: npm install
      - name: Install React ${{matrix.react-version}}
        if: ${{matrix.react-version}} != '17.x'
        run: npm install --no-save react@${{matrix.react-version}} react-dom@${{matrix.react-version}} react-test-renderer@${{matrix.react-version}}
      - name: Run tests
        run: npm run tests-only
